print("CADASTRO DE PACIENTE")
nome = input("Digite o nome: ")
idade = input("Digite a idade: ")
peso = input("Digite o seu peso: ")
altura = input("Digite a sua altura: ")
sexo = input("Digite o seu sexo: ")
print("Dados do paciente")
print("O nome é", nome)
print("A idade é", idade, "anos")
print("A altura é", altura, "m")
print("O peso é", peso, "Kg")
print("O sexo é", sexo)
